# -*- coding: utf-8 -*-
"""Emailapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H7gqlGkdIV-JAxMIaedpO9noSp0ens2A
"""

# streamlit_app.py
import streamlit as st
import joblib
from PIL import Image

@st.cache_resource
def load_models():
    tfidf = joblib.load("tfidf_vectorizer.joblib")
    model = joblib.load("best_email_classifier.joblib")
    return tfidf, model

st.set_page_config(page_title="HR Email Classifier", layout="wide")
st.title("HR Automatic Email Categorization")

tfidf, model = load_models()

st.sidebar.header("Single Email Prediction")
subject = st.sidebar.text_input("Subject", "")
body = st.sidebar.text_area("Body", "")
if st.sidebar.button("Classify"):
    raw = (subject + " " + body).strip()
    if not raw:
        st.sidebar.warning("Please enter subject or body text.")
    else:
        # use same cleaning function from notebook: for demo, implement minimal cleaning here
        import re, string
        from nltk.corpus import stopwords
        sw = set(stopwords.words('english'))
        def clean_demo(text):
            text = text.lower()
            text = re.sub(r"\S+@\S+", " ", text)
            text = re.sub(r"http\S+|www\S+|https\S+", " ", text)
            text = re.sub(r"\d+", " ", text)
            text = text.translate(str.maketrans("", "", string.punctuation))
            tokens = [t for t in text.split() if t.isalpha() and t not in sw and len(t)>2]
            return " ".join(tokens)
        cleaned = clean_demo(raw)
        X = tfidf.transform([cleaned])
        pred = model.predict(X)[0]
        st.success(f"Predicted category: **{pred}**")

st.header("Dataset preview & EDA")
# Show a sample of dataset
st.write("Example rows (from uploaded dataset):")
import pandas as pd
df = pd.read_json("/content/hr_support_emails_2025_6.json")
st.dataframe(df.sample(6))

st.markdown("**Notes:** This demo uses a TF-IDF + tuned classifier. For production, secure hosting and incremental retraining are recommended.")

